version: "3.8"

services:
  jenkins:
    build:
      context: .
      dockerfile: Dockerfile.jenkins
    container_name: jenkins
    ports:
      - "8080:8080"
      - "50000:50000"

    environment:
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=true

    volumes:
      - ./jenkins_home:/var/jenkins_home
      - ./jenkins/init.groovy.d:/var/jenkins_home/init.groovy.d:ro
      - ./kubeconfig/kubeconfig-kind.yaml:/var/jenkins_home/.kube/config

    networks:
      - jenkins-net
      - kind

    restart: unless-stopped

networks:
  jenkins-net:
    driver: bridge
  kind:
    external: true